// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV57zAc_N3b08rjLe22cmkTssNJc0r6pE',
    appId: '1:516531210842:web:785fc04548430540496663',
    messagingSenderId: '516531210842',
    projectId: 'todo-ea207',
    authDomain: 'todo-ea207.firebaseapp.com',
    storageBucket: 'todo-ea207.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFclR9z7aj-vY4IneBrwWHxfhdCtBAms',
    appId: '1:516531210842:android:5278bcbaedd8315d496663',
    messagingSenderId: '516531210842',
    projectId: 'todo-ea207',
    storageBucket: 'todo-ea207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYPZu5pO4AFUrRe0kna2sDZHB0rtJQKg',
    appId: '1:516531210842:ios:d4c8c9194cde2069496663',
    messagingSenderId: '516531210842',
    projectId: 'todo-ea207',
    storageBucket: 'todo-ea207.appspot.com',
    iosClientId: '516531210842-ort57n5cv03o4rlesua11ebga032tmt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYPZu5pO4AFUrRe0kna2sDZHB0rtJQKg',
    appId: '1:516531210842:ios:d4c8c9194cde2069496663',
    messagingSenderId: '516531210842',
    projectId: 'todo-ea207',
    storageBucket: 'todo-ea207.appspot.com',
    iosClientId: '516531210842-ort57n5cv03o4rlesua11ebga032tmt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
